apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    component: nats
spec:
  ports:
  - name: ""
    port: 4222
    protocol: TCP
    targetPort: 4222
  template:
    metadata:
      labels:
        component: nats
    spec:
      containers:
      - name: nats
        image: nats:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: tls-volume
            mountPath: /etc/nats/tls
        selector:
          name: "nats"
        env:
        - name: EXTRA
          value: -DV
        - name: TLS
          value: "true"
        - name: TLSCERT
          value: /etc/nats/tls/nats.pem
        - name: TLSKEY
          value: /etc/nats/tls/nats-key.pem
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        livenessProbe:
          tcpSocket:
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: tls-volume
        secret:
          secretName: tls-nats
          
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nats-primary
  name: nats-primary
spec:
  ports:
    - port: 4222
      targetPort: 4222
  selector:
    name: nats
---
apiVersion: v1
kind: Pod
metadata:
  labels:
          name: nats-master
  name: nats-master
spec:
  containers:
    - name: nats-master
      image: "nats:latest"
      ports:
        - containerPort: 4222
      command:
        - "--cluster nats://0.0.0.0:6222"
        - "--user ${user} --pass ${pass}"
      volumeMounts:
        - name: tls-volume
          mountPath: /etc/nats/tls
  volumes:
    - name: tls-volume
      emptyDir: {}

