apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: nats-service
  name: nats-service
spec: 
  ports:
    - port: 4222
  selector: 
    name: nats
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: nats
  labels: 
    name: nats
spec: 
  containers: 
    - image: nats
      name: nats
      ports: 
        - containerPort: 4222
          name: nats
