apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: nats
  name: nats
spec: 
  ports:
    - port: 4222
  selector: 
    name: nats-pod
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: nats-pod
  labels: 
    name: nats-pod
spec: 
  containers: 
    - image: nats
      name: nats-pod
      ports: 
        - containerPort: 4222
          name: nats-pod
