kind: "Service"
apiVersion: "v1"
metadata: 
  name: "nats"
  labels: 
    app: "nats"
spec: 
  containers: 
    - name: "nats"
      image: "nats:latest"
      ports: 
          port: 4222
  selector: 
    app: "nats"
