.catalog:
  name: Nats
  version: 3.2-rancher1
  description: Nats Cluster
  questions:
    - variable: "sec_no"
      label: "Number of Secondary nodes"
      required: true
      type: int
      default: 2
      description: "should be a number"
    - variable: "tls_volume"
      label: "TLS volume name"
      required: true
      type: int
      default: "tls-volume"
      description: "should be a volume name"
